name: ci-golang-workflow
on: 
  pull_request:  ## needs to wait the check-application workflow pass to merge in develop
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:           
    #     go: ['1.14', '1.15'] ## run in different version 

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go   

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build        ## When up put id, you can get the result of this step and use in other step
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: snitram13/continuous-integration-go:latest